"""empty message

Revision ID: b297e5c58a16
Revises: 
Create Date: 2020-12-14 23:49:04.312534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b297e5c58a16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_user_password_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_user_password_key', 'user', ['user_password'])
    # ### end Alembic commands ###
